name: FLPNO
favicon: null
layout_spectrum: 0.6683367190416902
typography_spectrum: 0.7578756231814623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9442090343218297
  lightness: 0.8266149968840182
  saturation: 0.4710977962240577
  rhythmicContrast: 0.2728251039516181
purpose: []
