name: FLPNO
favicon: null
layout_spectrum: 0.75037
typography_spectrum: 0.35072
title: FLPNO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e30011'
    - '#f8d80b'
    - '#0068ff'
    - '#f9818a'
  brandStrength: 0.9442090343218297
  lightness: 0.8266149968840182
  saturation: 0.5
  rhythmicContrast: 0.2728251039516181
purpose: []
